/*
 * This source file was generated by the Gradle 'init' task
 */
package me.eeshe.grammyswrapped;

import net.dv8tion.jda.api.hooks.ListenerAdapter;

public class App extends ListenerAdapter {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    new Bot().start();
  }
}
