/*
 * This source file was generated by the Gradle 'init' task
 */
package me.eeshe.grammyswrapped;

public class App {

  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    new Bot().start();
  }
}
